[package]
name = "quickstart-local-laws"
version = "0.1.0"
edition = "2024"

[dependencies]
delta_local_laws = { version = "0.6.10", registry = "delta" }
sp1-zkvm = "5.2"
serde = { version = "1", features = ["derive"] }
bincode = { version = "2", features = ["serde"] }
